### ISSUE TITLE
I need support of the GitHub native TODO syntax for MD files

### ISSUE THREAD

**Issue by 1st** [fabiospampinato/vscode-todo-plus#297]
I like your extension a lot. But one problem., when I commit the `TODO.nd` file to GitHub it doesn't look nice like it should.

The default schema of the GitHub is next:
```
Example:
- [ ] active todo item
- [x] done todo item
```

Example:
- [ ] active todo item
- [x] done todo item

I've tried to play with settings of the extension but no luck. when I set the `box` to be `- [ ] ` and done to be `- [x]` it just duplicates the string each time when I mark task done/active. Maybe i's a bug?!

Would be nice to have the support of the GitHub Markdown todo syntax in your extension.

Thank you,
Anton

**Comment by 1st** [comment]
P.S. I do not nee the "cancelled" items, so don't care about support of such option.

**Comment by fabiospampinato** [comment]
> I've tried to play with settings of the extension but no luck. when I set the box to be - [ ] and done to be - [x] it just duplicates the string each time when I mark task done/active. Maybe i's a bug?!

Those aren't valid strings, the valid ones are listed in the readme.

I'd consider this as an out-of-scope request, this extension isn't meant to work with Markdown, there should probably be something like this working with plain markdown files but we can't just tweak this one and have it working for Markdown files well.
